### PR TITLE
CoffeeScript support for grammars and snippets

### LINKED ISSUE #8: Coffeescript support
Great package! Is it planned to support coffescript also?

### PR DESCRIPTION
**Pull request by schrislambert**
Hi, @awatson1978 , great package.  This should add support for CoffeeScript.

fixes #8

### CODE REVIEW

**Comment by maxnowack** [comment]
+1

**Comment by awatson1978** [comment]
I don't see anything immediately problematic.  This will likely get merged in as-is.  Hopefully this week.  But I need to squeeze it in among a half-dozen other projects.

**Comment by awatson1978** [comment]
Thanks for the pull request.  In the future, if you make the pull-request against the develop branch, it will help get the pull-request merged faster.

**Comment by awatson1978** [comment]
Just as a note to everybody asking for CoffeeScript support:  

Atom apparently parses it's grammars alphabetically in the configuration page, and when the new version was published, CoffeeScript was showing up at the top of the config page, as if it were the default or primary language for this package.  This sort of irked me since Meteor Principle 1 is Pure Javascript.    

I was about to revert the change, and take it out; but instead have settled on renaming the grammar to ``KoffeeScript``.  Since the letter K follows the letter J in the alphabet, JavaScript is at the beginning of the config file; and all is well.    

Please don't submit issues saying that CoffeeScript is misspelled.  If I'm going to be maintaining this package, it's getting spelled with a K.  

Anyhow.  ``meteor-api`` version v2.12.0 just published with KoffeeScript support.  Enjoy.

**Pull request merged**
